/*
IN this we handle error which is generated by promises.

catch(): this function help us to resolve errors when promise get rejected.

*imp->  catch function only handle error of then() which are above it.

*/

const cart=["milk","soap","pants"];

function createOrder(cart)
{
    const promise1=new Promise(function(resolve,reject){
    
        if(!validatecart(cart))
        {
            const err=new Error("cart is not valid");
            reject(err);
        }

        const orderid="11111";
        resolve(orderid);
    });

    return promise1;
}


function validatecart(cart)
{
    return true;
}

function proceedtopayment(orderid)
{
    return new Promise(function(resolve,reject)
    {
        resolve("payment successful");
    });
}


createOrder(cart)
.then(function (orderid){
    console.log(orderid);
})
.then(function(orderid){
    proceedtopayment(orderid);
})
.catch(function (err)
{
    console.log(err.message);
});

